# Microgateway ports
ports:
   http: 9090
   https: 
   key_alias: ssos
 
# Microgateway API endpoint base path
api_endpoint:
    base_path: /gateway
 
 
# API Gateway configuration 
api_gateway:
   url: http://dcssuv01:4444
   user: Administrator
   password: manage
   dir: /home/Administrator/Microgateway/
   retain_settings: true
   
 #service registry
service_registries:
- type: serviceRegistryAlias
  id: ServiceConsulDefault
  name: ServiceConsulDefault
  description: Service Consul is a tool for discovering and configuring services in
    IT infrastructure.
  owner: Administrator
  endpointURI: http://vmcrosscluster2:8500/v1
  heartBeatInterval: 0
  password: ''
  customHeaders:
    X-Consul-Token: ''
  discoveryInfo:
    path: "/catalog/service/{serviceName}"
    httpMethod: GET
  registrationInfo:
    path: "/agent/service/register"
    httpMethod: PUT
  deRegistrationInfo:
    path: "/agent/service/deregister/{serviceId}"
    httpMethod: PUT
  serviceRegistryType: SERVICE_CONSUL
  connectionTimeout: 30
  readTimeout: 30
 
# Specifying assets to download from API Gateway
downloads:
   apis: FlightTracking
   
   
# Microgateway admin API configuration
admin_api:
    admin_path: /rest/microgateway
microgatewayPool:
    microgatewayPoolName: DEMO
    microgatewayPoolDescription: All the partner APIs running on Microgateway are available on this pool.	
    
    
# Specify the runtime authorization method
policies:
   user_auth: delegated
   
   
# Microgateway logging configuration
logging:
   level: ERROR
   path: logs
