# Microgateway ports
ports:
   http: 9090
   https: 
   key_alias: ssos
 
# Microgateway API endpoint base path
api_endpoint:
    base_path: /gateway
 
 
# API Gateway configuration 
api_gateway:
   url: http://daehpresal32272.daedmz.loc:11072
   user: Administrator
   password: Demo2019!
   dir: /home/Administrator/Microgateway/
   retain_settings: true
   
 
# Specifying assets to download from API Gateway
downloads:
   apis: getSAPData
   
   
# Microgateway admin API configuration
admin_api:
    admin_path: /rest/microgateway
microgatewayPool:
    microgatewayPoolName: DEMO
    microgatewayPoolDescription: All the partner APIs running on Microgateway are available on this pool.	
    
    
# Specify the runtime authorization method
policies:
   user_auth: delegated
   
   
# Microgateway logging configuration
logging:
   level: ERROR
   path: logs
